src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Util\Util;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 *
 * @ORM\Table(name="blog")
 * @ORM\Entity(repositoryClass="App\Repository\BlogRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Blog
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer", options={"unsigned":true})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $keyword;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $metaDescription;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;
    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $dateAdded;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $status = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $position = 1;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\DateTime
     */
    private $dateUpdated;

    /**
     * @ORM\OneToMany(targetEntity="Topic", mappedBy="blog", cascade={"remove"})
     * @ORM\OrderBy({"position" = "ASC"})
     */
    protected $topics;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="blogs")
     * @Assert\NotBlank
     */
    protected $user;

//    /**
//     * @ORM\ManyToOne(targetEntity="User", mappedBy="blogs")
//     */
//    protected $user;

    public function __construct()
    {
        $this->dateAdded = new \DateTime();
        $this->topics = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Blog
     */
    public function setId(int $id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Blog
     */
    public function setTitle(string $title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * @param string $summary
     * @return Blog
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
        return $this;
    }

    /**
     * @return string
     */
    public function getNotes(): ?string
    {
        return $this->notes;
    }

    /**
     * @param string $notes
     * @return Blog
     */
    public function setNotes(string $notes)
    {
        $this->notes = $notes;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateAdded(): ?\DateTime
    {
        return $this->dateAdded;
    }

    /**
     * @param \DateTime $dateAdded
     * @return Blog
     */
    public function setDateAdded(\DateTime $dateAdded)
    {
        $this->dateAdded = $dateAdded;
        return $this;
    }

    /**
     * @return int
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return Blog
     */
    public function setStatus(int $status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdated(): ?\DateTime
    {
        return $this->dateUpdated;
    }

    /**
     * @param \DateTime $dateUpdated
     * @return Blog
     */
    public function setDateUpdated(\DateTime $dateUpdated)
    {
        $this->dateUpdated = $dateUpdated;
        return $this;
    }

    /**
     */
    public function updateDate()
    {
        $this->dateUpdated = new \DateTime();
    }

    /**
     * @return ArrayCollection[]|Topic[]
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * @param mixed $topics
     * @return Blog
     */
    public function setTopics($topics)
    {
        $this->topics = $topics;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     * @return Blog
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return string
     */
    public function getKeyword(): ?string
    {
        return $this->keyword;
    }

    /**
     * @param string $keyword
     * @return Blog
     */
    public function setKeyword($keyword)
    {
        $this->keyword = $keyword;
        return $this;
    }

    /**
     * @return string
     */
    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    /**
     * @param string $metaDescription
     * @return Blog
     */
    public function setMetaDescription($metaDescription)
    {
        $this->metaDescription = $metaDescription;
        return $this;
    }

    public function getStatusText()
    {
        switch ($this->getStatus()) {

            case 6:
                return 'Archived';
            case 0:
                return 'Draft';
            case 1:
                return 'Pending';
            case 2:
                return 'In Progress';
            case 3:
                return 'Needs Review';
            case 4:
                return 'Ready';
            case 5:
                return 'Published';
        }
    }

    /**
     * Get the word count just for the summary
     *
     * @return mixed
     */
    public function getBlogWordCount()
    {
        $text = html_entity_decode(strip_tags($this->getSummary()));

        return str_word_count($text);
    }

    /**
     * Get the word count for the summary and all the topics combined
     *
     * @return int
     */
    public function getTotalWordCount()
    {
        $text = html_entity_decode(strip_tags($this->getSummary()));

        $total = str_word_count($text);

        foreach ($this->getTopics() as $topic) {
            $total += $topic->getWordCount();
        }

        return $total;
    }

    public function getReadingTime()
    {
        $text = $this->getTotalWordCount();

        return Util::readingTime($text);
    }

    /**
     * @return int
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @param int $position
     * @return Blog
     */
    public function setPosition(int $position)
    {
        $this->position = $position;
        return $this;
    }

    public function getPreview()
    {

        $text = $this->getTitle();

        if ($summary = $this->getSummary()) {
            $text .= "<br>$summary";
        }

        foreach ($this->getTopics() as $topic) {
            $text .="<br>".$topic->getTitle();
            $text .="<br>".$topic->getContent();
        }

        return $text;

    }


}

src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'attr' => ['class' => 'wordcount']
            ])
            ->add('keyword')
            ->add('meta_description', TextareaType::class, [
                'attr' => ['rows' => 3, 'class' => 'wordcount']
            ])
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'Archived' => 6,
                    'Draft' => 0,
                    'Pending' => 1,
                    'In Progress' => 2,
                    'Needs Review' => 3,
                    'Ready' => 4,
                    'Published' => 5,
                ]
            ])
            ->add('notes', null, [
                'attr' => ['rows' => 6]
            ])
            ->add('summary', TextareaType::class, [
                'label' => 'Intro Paragraph',
                'attr' => ['rows' => 10, 'class' => 'editor']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }

}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Form\BlogType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/panel/blog", name="blog_")
 */
class BlogController extends Controller
{

    /**
     * @param Request $request
     * @Route("/", name="home")
     */
    public function indexAction(Request $request)
    {

        $em = $this->getDoctrine()->getManager();
        $draftBlogs = $em->getRepository('App:Blog')->getBlogs($this->getUser());
        $publishedBlogs = $em->getRepository('App:Blog')->getBlogs($this->getUser(), 1);
        $archivedBlogs = $em->getRepository(Blog::class)->getBlogs($this->getUser(), 2);

        return $this->render('blog/index.html.twig', [
            'draftBlogs' => $draftBlogs,
            'publishedBlogs' => $publishedBlogs,
            'archivedBlogs' => $archivedBlogs
        ]);
    }

    /**
     * @param Request $request
     * @Route("/edit/{blog_id}", name="edit", options={"expose": true})
     */
    public function editAction($blog_id = null, Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $blog = new Blog();
        $blog->setUser($this->getUser());
        $blog->setUser($this->getUser());
        if ($blog_id) {
            $blog = $em->getRepository('App:Blog')->findOneBy([
                'id' => $blog_id,
                'user' => $this->getUser()
            ]);
        }

        $form = $this->createForm(BlogType::class, $blog);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $blog->updateDate();
            $em->persist($blog);
            $em->flush();

            if ($request->isXmlHttpRequest()) {
                return new JsonResponse(['status' => 'success', 'blog_id' => $blog->getId()]);
            }

            return $this->redirectToRoute('topic_home', ['blog_id' => $blog->getId()]);

        }

        return $this->render('blog/edit.html.twig', [
            'form' => $form->createView(),
        ]);

    }

    /**
     * @Route("/preview/{blog_id}", name="preview")
     */
    public function previewAction($blog_id)
    {

        $em = $this->getDoctrine()->getManager();
        $blog = $em->getRepository(Blog::class)->find($blog_id);
        $text = $blog->getPreview();

        $key = "LGUKO3Z56MCZ2WEY8J78AIP23116NYPU";

        $url = 'https://api.readable.com/api/text/'; // The API endpoint you want to interact with
        $request_time = time(); // Time of request
        $api_signature = md5($key . $request_time);

        $postItems = ['text' => $text];
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);


        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($postItems));
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('API_SIGNATURE: ' . $api_signature, 'API_REQUEST_TIME: ' . $request_time));
        $file = curl_exec($ch);
        curl_close($ch);
//
        $results = json_decode($file, true);

        return $this->render('blog/preview.html.twig', [
            'blog' => $blog,
            'results' => $results
        ]);

    }

    /**
     * @Route("/order", name="update_order", options={"expose": true}, methods={"POST"})
     */
    public function updateOrderAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $blogs = $em->getRepository(Blog::class)->getBlogs($this->getUser());
        $orderedBlogs = $request->request->get('blog');

        /** @var Blog $blog */
        foreach ($blogs as $blog) {

            $position = array_search($blog->getId(), $orderedBlogs);
            $blog->setPosition($position);
            $em->persist($blog);

        }

        $em->flush();
        return new JsonResponse([$request->request->all()]);


    }

    /**
     * @Route("/delete/{blog_id}", name="delete", options={"expose": true}, methods={"DELETE"})
     */
    public function deleteAction($blog_id)
    {
        $em = $this->getDoctrine()->getManager();
        $blog = $em->getRepository(Blog::class)->findOneBy([
            'user' => $this->getUser(),
            'id' => $blog_id
        ]);

        if (!$blog)
            throw new NotFoundHttpException();

        $em->remove($blog);
        $em->flush();

        return new JsonResponse(['status' => 'success']);

    }



}

templates/blog/_blogs.html.twig
<table class="table table-hover">
    <thead>
    <tr>
            {% if reordering is defined %}
            <th style="width:50px;"></th>
        {% endif %}
        <th>Title</th>
        <th class="text-center" style="width:175px;">Status</th>
        <th class="text-center" style="width:225px;">Updated</th>
        <th class="text-center" style="width: 175px">Words</th>
        <th class="text-right" style="width:25px;">Options</th>
    </tr>
    </thead>
    <tbody class="sortable">
    {% for blog in blogs %}
        <tr id="blog_{{ blog.id }}">

            {% if reordering is defined %}
                <td>
                    <i class="fal fa-bars handle" style="cursor: move"></i> &nbsp;
                </td>
            {% endif %}

            <td>
                {{ blog.title }}
            </td>

            {{ include('template/status_color.html.twig', {item: blog}) }}

            <td class="text-center">
                {% if blog.dateUpdated %}
                    {{ blog.dateUpdated|date }}
                {% else %}
                    Never
                {% endif %}
            </td>
            <td class="text-center">
                {{ blog.totalWordCount }}
            </td>
            <td class="text-right">

                <div class="dropdown">
                    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fal fa-edit"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ path('blog_edit', {'blog_id': blog.id}) }}">
                            Edit Blog
                        </a>
                        <a class="dropdown-item" href="{{ path('topic_home', {'blog_id': blog.id}) }}">
                            Topics ({{ blog.topics|length }})
                        </a>
                        <a class="dropdown-item" href="{{ path('blog_preview', {'blog_id': blog.id}) }}">
                            Preview
                        </a>
                        <a class="dropdown-item btn-blog-delete" href="#" data-blog-id="{{ blog.id }}">Delete</a>
                    </div>
                </div>

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/blog/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
        <div class="col-6">
            <a href="{{ path('blog_home') }}"> Back to Blogs</a><br/>
            <h3>Edit Blog</h3>
        </div>
        <div class="col-6">
            <div class="block-saving pull-right" style="padding: 8px;">
                <small class="blog-saving" style="display:none;">
                    <i class="fas fa-spinner fa-pulse"></i>
                    Saving
                </small>

                <small class="blog-saved" style="display: none;">
                </small>
            </div>

        </div>
    </div>


    <div id="blog-id" data-id="{{ form.vars.value.id }}"></div>

    {{ form_start(form, {method: 'post', attr: {novalidate: 'novalidate'}}) }}

    <div class="row">
        <div class="form-group col-sm-6">
            <label for="" class="">Blog Title
                <small>(Max 50–60 characters)</small>
            </label>

            <div class="input-group">
                {{ form_widget(form.title) }}
                <span id="title-length" class="input-group-addon bg-warning text-center form-control-plaintext"
                      data-min="0" data-max="50" style="width:50px;">
                    {{ form.vars.value.title|length }}
                </span>
            </div>
        </div>


        <div class="form-group col-sm-6">
            <label for="" class="">Focus Keyword
                {#<small>(Max 50–60 characters)</small>#}
            </label>
            {{ form_widget(form.keyword) }}
        </div>
    </div>

    <div class="form-group">
        <label for="" class="">Meta Description
            <small>(50–300 characters)</small>
        </label>

        <div class="input-group">
            {{ form_widget(form.meta_description) }}
            <span id="meta-length" class="input-group-addon bg-success text-center form-control-plaintext" data-min="50"
                  data-max="300" style="width:50px;">
                {{ form.vars.value.metaDescription|length }}
            </span>
        </div>
    </div>

    {{ form_rest(form) }}

    <div class="row">
        <div class="col-sm-6">
            Word Count: <span id="word-count">{{ form.vars.value.blogWordCount }}</span><br/>
        </div>
        <div class="col-sm-6">

            <div class="form-group text-center">
                <button class="btn btn-primary pull-right" type="submit">
                    <i class="fa fa-save" aria-hidden="true"></i> Save
                </button>

                <div class="block-saving pull-right" style="padding: 8px;">
                    <small class="blog-saving" style="display:none;">
                        <i class="fas fa-spinner fa-pulse"></i>
                        Saving
                    </small>

                    <small class="blog-saved" style="display: none;">
                    </small>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script defer="defer" src="{{ asset('build/js/blog.js') }}"></script>
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <a class="btn btn-primary" href="{{ path('blog_edit') }}">New Article</a>
    <br/><br/>


    <ul class="nav nav-tabs">
        <li class="nav-item active">
            <a class="nav-link active" data-toggle="tab" href="#open">Open</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#published"> Published </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#archived"> Archived </a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="open">
            {{ include('blog/_blogs.html.twig', {blogs: draftBlogs, reordering  : true}) }}
        </div>

        <div class="tab-pane fade" id="published">
            {{ include('blog/_blogs.html.twig', {blogs: publishedBlogs}) }}
        </div>

        <div class="tab-pane fade" id="archived">
            {{ include('blog/_blogs.html.twig', {blogs: archivedBlogs}) }}
        </div>
    </div>

{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script defer="defer" src="{{ asset('build/js/blog.js') }}"></script>
{% endblock %}

templates/blog/preview.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
        <div class="col-6">
            <a href="{{ path('blog_home') }}" class="btn btn-sm btn-primary"> Back to blogs</a>
            <a href="{{ path('blog_edit', {blog_id: blog.id}) }}" class="btn btn-sm btn-primary"> Edit Blog</a>
            <a href="{{ path('topic_home', {blog_id: blog.id}) }}" class="btn btn-sm btn-primary"> Edit Topics</a>

            <br/><br/>
            Estimate Reading Time: {{ blog.readingTime }}<br/>
            Word Count: {{ blog.totalWordCount }}<br/>
        </div>

        <div class="col-3 text-right">
            <small>
                Paragraphs: {{ results.paragraph_count }}<br>
                Sentences: {{ results.sentence_count }}<br>
                Letters: {{ results.letter_count }}<br>
            </small>
        </div>
        <div class="col-3 text-right">
            <small>
                Speaking Time: {{ results.speaking_time }}<br>
                Flesch Score: {{ results.flesch_kincaid_grade_level }}<br>
                Gunning Fog Score: {{ results.gunning_fog_score }}<br>
            </small>

        </div>
    </div>



    <br/>
    <div style="padding:20mm; border: 1px solid #b3b3b3;">
        <div class="text-center">
            <h2>{{ blog.title }}</h2>
        </div>

        {% if blog.summary %}
            <p>{{ blog.summary|raw }}</p>
        {% endif %}

        {% for topic in blog.topics %}
            <h3>{{ topic.title }}</h3>

            <p>{{ topic.content|raw }}</p>
        {% endfor %}

    </div>


{% endblock %}