src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Util\Util;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 *
 * @ORM\Table(name="blog")
 * @ORM\Entity(repositoryClass="App\Repository\BlogRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Blog
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer", options={"unsigned":true})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $keyword;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $metaDescription;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;
    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $dateAdded;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $status = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $position = 1;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\DateTime
     */
    private $dateUpdated;

    /**
     * @ORM\OneToMany(targetEntity="Topic", mappedBy="blog", cascade={"remove"})
     * @ORM\OrderBy({"position" = "ASC"})
     */
    protected $topics;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="blogs")
     * @Assert\NotBlank
     */
    protected $user;

//    /**
//     * @ORM\ManyToOne(targetEntity="User", mappedBy="blogs")
//     */
//    protected $user;

    public function __construct()
    {
        $this->dateAdded = new \DateTime();
        $this->topics = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Blog
     */
    public function setId(int $id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Blog
     */
    public function setTitle(string $title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * @param string $summary
     * @return Blog
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
        return $this;
    }

    /**
     * @return string
     */
    public function getNotes(): ?string
    {
        return $this->notes;
    }

    /**
     * @param string $notes
     * @return Blog
     */
    public function setNotes(string $notes)
    {
        $this->notes = $notes;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateAdded(): ?\DateTime
    {
        return $this->dateAdded;
    }

    /**
     * @param \DateTime $dateAdded
     * @return Blog
     */
    public function setDateAdded(\DateTime $dateAdded)
    {
        $this->dateAdded = $dateAdded;
        return $this;
    }

    /**
     * @return int
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return Blog
     */
    public function setStatus(int $status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdated(): ?\DateTime
    {
        return $this->dateUpdated;
    }

    /**
     * @param \DateTime $dateUpdated
     * @return Blog
     */
    public function setDateUpdated(\DateTime $dateUpdated)
    {
        $this->dateUpdated = $dateUpdated;
        return $this;
    }

    /**
     */
    public function updateDate()
    {
        $this->dateUpdated = new \DateTime();
    }

    /**
     * @return ArrayCollection[]|Topic[]
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * @param mixed $topics
     * @return Blog
     */
    public function setTopics($topics)
    {
        $this->topics = $topics;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     * @return Blog
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return string
     */
    public function getKeyword(): ?string
    {
        return $this->keyword;
    }

    /**
     * @param string $keyword
     * @return Blog
     */
    public function setKeyword($keyword)
    {
        $this->keyword = $keyword;
        return $this;
    }

    /**
     * @return string
     */
    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    /**
     * @param string $metaDescription
     * @return Blog
     */
    public function setMetaDescription($metaDescription)
    {
        $this->metaDescription = $metaDescription;
        return $this;
    }

    public function getStatusText()
    {
        switch ($this->getStatus()) {

            case 6:
                return 'Archived';
            case 0:
                return 'Draft';
            case 1:
                return 'Pending';
            case 2:
                return 'In Progress';
            case 3:
                return 'Needs Review';
            case 4:
                return 'Ready';
            case 5:
                return 'Published';
        }
    }

    /**
     * Get the word count just for the summary
     *
     * @return mixed
     */
    public function getBlogWordCount()
    {
        $text = html_entity_decode(strip_tags($this->getSummary()));

        return str_word_count($text);
    }

    /**
     * Get the word count for the summary and all the topics combined
     *
     * @return int
     */
    public function getTotalWordCount()
    {
        $text = html_entity_decode(strip_tags($this->getSummary()));

        $total = str_word_count($text);

        foreach ($this->getTopics() as $topic) {
            $total += $topic->getWordCount();
        }

        return $total;
    }

    public function getReadingTime()
    {
        $text = $this->getTotalWordCount();

        return Util::readingTime($text);
    }

    /**
     * @return int
     */
    public function getPosition(): ?int
    {
        return $this->position;
    }

    /**
     * @param int $position
     * @return Blog
     */
    public function setPosition(int $position)
    {
        $this->position = $position;
        return $this;
    }

    public function getPreview()
    {

        $text = $this->getTitle();

        if ($summary = $this->getSummary()) {
            $text .= "<br>$summary";
        }

        foreach ($this->getTopics() as $topic) {
            $text .="<br>".$topic->getTitle();
            $text .="<br>".$topic->getContent();
        }

        return $text;

    }


}

src/Entity/Topic.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;


use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Table(name="topic")
 * @ORM\Entity(repositoryClass="App\Repository\TopicRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Topic
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer", options={"unsigned":true})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $content = '';


    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;


    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $wordCount = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $status = 0;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $position = 1;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $dateAdded;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     * @Assert\DateTime
     */
    private $dateUpdated;

    /**
     * @ORM\ManyToOne(targetEntity="Blog", inversedBy="topics")
     */
    protected $blog;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="topics")
     * @Assert\NotBlank
     */
    protected $user;


    public function __construct()
    {
        $this->dateAdded = new \DateTime();
    }

    /**
     * @return int
     */
    public function getId(): ? int
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Topic
     */
    public function setId(int $id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle(): ? string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Topic
     */
    public function setTitle(string $title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getContent(): ? string
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return Topic
     */
    public function setContent($content)
    {
        $this->content = $content;

        $text = html_entity_decode(strip_tags($content));
        $this->setWordCount(str_word_count($text));
        return $this;
    }

    /**
     * @return int
     */
    public function getStatus(): ? int
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return Topic
     */
    public function setStatus(int $status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateAdded(): ? \DateTime
    {
        return $this->dateAdded;
    }

    /**
     * @param \DateTime $dateAdded
     * @return Topic
     */
    public function setDateAdded(\DateTime $dateAdded)
    {
        $this->dateAdded = $dateAdded;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdated(): ? \DateTime
    {
        return $this->dateUpdated?:$this->getDateAdded();
    }

    /**
     * @param \DateTime $dateUpdated
     * @return Topic
     */
    public function setDateUpdated(\DateTime $dateUpdated)
    {
        $this->dateUpdated = $dateUpdated;
        return $this;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function updateDate()
    {
        $this->dateUpdated = new \DateTime();
        if ($blog = $this->getBlog()) {
            $this->getBlog()->updateDate();
        }
    }


    /**
     * @return Blog
     */
    public function getBlog()
    {
        return $this->blog;
    }

    /**
     * @param mixed $blog
     * @return Topic
     */
    public function setBlog($blog)
    {
        $this->blog = $blog;
        return $this;
    }

    /**
     * @return string
     */
    public function getNotes(): ? string
    {
        return $this->notes;
    }

    /**
     * @param string $notes
     * @return Topic
     */
    public function setNotes(string $notes)
    {
        $this->notes = $notes;
        return $this;
    }

    /**
     * @return int
     */
    public function getPosition(): ? int
    {
        return $this->position;
    }

    /**
     * @param int $position
     * @return Topic
     */
    public function setPosition(int $position)
    {
        $this->position = $position;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     * @return Topic
     */
    public function setUser($user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return int
     */
    public function getWordCount(): ? int
    {
        return $this->wordCount;
    }

    /**
     * @param int $wordCount
     * @return Topic
     */
    public function setWordCount(int $wordCount)
    {
        $this->wordCount = $wordCount;
        return $this;
    }

    public function getStatusText()
    {
        switch ($this->getStatus()) {

            case 0: return 'Draft';
            case 1: return 'Pending';
            case 2: return 'In Progress';
            case 3: return 'Needs Review';
            case 4: return 'Ready';
            case 5: return 'Published';
        }
    }



}

src/Controller/TopicController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Topic;
use App\Form\BlogType;
use App\Form\TopicType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/panel/blog/{blog_id}", name="topic_")
 */
class TopicController extends Controller
{

    /**
     * @param Request $request
     * @Route("/topic", name="home")
     */
    public function indexAction($blog_id, Request $request)
    {

        $em = $this->getDoctrine()->getManager();
        $blog = $em->getRepository('App:Blog')->find($blog_id);
        $topics = $em->getRepository('App:Topic')->getTopics($blog);

        return $this->render('topic/index.html.twig', [
            'blog' => $blog,
            'topics' => $topics,
        ]);
    }

    /**
     * @param Request $request
     * @Route("/topic/edit/{topic_id}", name="edit", options={"expose": true})
     */
    public function editAction($blog_id, $topic_id = null, Request $request)
    {

        $em = $this->getDoctrine()->getManager();
        $blog = $em->getRepository('App:Blog')->find($blog_id);

        $topic = new Topic();
        $topic->setUser($this->getUser());
        $topic->setBlog($blog);

        if ($topic_id) {
            $topic = $em->getRepository('App:Topic')->findOneBy(['blog' => $blog, 'id' => $topic_id]);
            $topic->setUser($this->getUser());
        }

        if (!$topic->getId() && $lastTopic = $blog->getTopics()->last()) {
            $position = $lastTopic->getPosition() + 1;
            $topic->setPosition($position);
        }

        $form = $this->createForm(TopicType::class, $topic);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($topic);
            $em->flush();
            if ($request->isXmlHttpRequest()) {
                return new JsonResponse(['status' => 'success', 'topic_id' => $topic->getId()]);
            }

            return $this->redirectToRoute('topic_home', ['blog_id' => $blog_id]);

        }


        $topics = $em->getRepository('App:topic')->findAll();

        return $this->render('topic/edit.html.twig', [
            'form' => $form->createView(),
            'topics' => $topics
        ]);

    }

    /**
     * @Route("/topic/order", name="update_order", options={"expose": true}, methods={"POST"})
     */
    public function updateOrderAction($blog_id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $blog = $em->getRepository('App:Blog')->find($blog_id);

        if (!$blog)
            throw new BadRequestHttpException('Cannot find that blog');


        $topics = $request->request->get('topic');

        foreach ($blog->getTopics() as $topic) {

            $position = array_search($topic->getId(), $topics);
            $topic->setPosition($position);
            $em->persist($topic);
        }

        $em->flush();
        return new JsonResponse([$request->request->all()]);


    }

    /**
     * @Route("/topic/delete/{topic_id}", name="delete", options={"expose": true}, methods={"DELETE"})
     */
    public function deleteAction($topic_id)
    {
        $em = $this->getDoctrine()->getManager();
        $topic = $em->getRepository('App:Topic')->findOneBy([
            'user' => $this->getUser(),
            'id' => $topic_id
        ]);

        if (!$topic)
            throw new NotFoundHttpException();

        $em->remove($topic);
        $em->flush();

        return new JsonResponse(['status' => 'success']);

    }

}

templates/topic/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ form.vars.value.blog.title }} | {% endblock %}

{% block body %}

{#{{ dump(form.vars) }}#}



    <div class="row">
        <div class="col-6">
            <a href="{{ path('topic_home', {blog_id:form.vars.value.blog.id}) }}"> Back to Topics</a> |
            <a href="{{ path('blog_home') }}"> Back to Blogs</a><br/>

            <h3>Edit Topic</h3>

        </div>
        <div class="col-6">
            <div class="block-saving pull-right" style="padding: 8px;">
                <small class="topic-saving" style="display:none;">
                    <i class="fas fa-spinner fa-pulse"></i>
                    Saving
                </small>

                <small class="topic-saved" style="display: none;">
                </small>
            </div>

        </div>
    </div>



    <div id="blog-id" data-id="{{ form.vars.value.blog.id }}"></div>
    <div id="topic-id" data-id="{{ form.vars.value.id }}"></div>

    {{ form_start(form, {method: 'post', attr: {novalidate: 'novalidate'}}) }}
    {{ form_rest(form) }}

    <div class="row">
        <div class="col-sm-6">
            Word Count: <span id="word-count">{{ form.vars.value.wordCount }}</span><br/>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <button class="btn btn-primary pull-right" type="submit">
                    <i class="fal fa-save" aria-hidden="true"></i> Save
                </button>

                <div class="block-saving pull-right" style="padding: 8px;">
                    <small class="topic-saving" style="display:none;">
                        <i class="fas fa-spinner fa-pulse"></i>
                        Saving
                    </small>

                    <small class="topic-saved" style="display: none;">
                    </small>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form) }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script defer="defer" src="{{ asset('build/js/topic.js') }}"></script>
{% endblock %}

templates/topic/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ blog.title }} | {% endblock %}

{% block body %}

    <a href="{{ path('blog_home') }}"> Back to blogs</a>

    <div>

        <h3 style="display: inline-block">{{ blog.title }}</h3>
        <a href="{{ path('blog_edit', {blog_id: blog.id}) }}" class="btn btn-primary btn-sm">edit</a>
        <a href="{{ path('blog_preview', {blog_id: blog.id}) }}" class="btn btn-primary btn-sm">preview</a>
    </div>
    Total Word Count: {{ blog.totalWordCount }}<br/>

    <br/>

    <a class="btn btn-primary" href="{{ path('topic_edit', {'blog_id': blog.id}) }}">New Topic</a>
    <br/><br/>

    <form id="blog" data-id="{{ blog.id }}">
        <table class="table table-hover">
            <thead>
            <tr>
                <th style="width:50px;"></th>
                <th>Topic</th>
                <th style="width:125px;">Words</th>
                <th class="text-center" style="width:200px;">Status</th>
                <th style="width:225px;">Last Updated</th>
                <th class="text-right" style="width:100px;">Options</th>
            </thead>
            <tbody class="sortable">
            {% for topic in topics %}
                <tr id="topic_{{ topic.id }}" >
                    <td>
                        <i class="fal fa-bars handle" style="cursor: move"></i> &nbsp;
                    </td>
                    <td>
                        {{ topic.title }}
                    </td>
                    <td>
                        {{ topic.wordCount }}
                    </td>
                    {{ include('template/status_color.html.twig', {item: topic}) }}

                    {#<td>#}
                        {#{{ topic.statusText }}#}
                    {#</td>#}
                    <td>
                        {{ topic.dateUpdated|date }}
                    </td>
                    <td class="text-right">
                        <a href="{{ path('topic_edit', {'blog_id': topic.blog.id, 'topic_id': topic.id}) }}"
                           class="btn btn-primary btn-sm">
                            <i class="far fa-edit"></i>
                        </a>
                        <div href="#" class="btn btn-danger btn-sm btn-topic-delete"
                             data-blog-id="{{ topic.blog.id }} "data-id="{{ topic.id }}">
                            <i class="far fa-trash-alt"></i>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>




{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script defer="defer" src="{{ asset('build/js/topic.js') }}"></script>
{% endblock %}